version: '3.8'

services:
  finances:
    build:
      context: ./FinancesApi
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:8080"
      - "5001:8081"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production