version: '3.8'

services:
  finances:
    build:
      context: ./FinancesApi
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5051"  # host:container
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production